### ISSUE TITLE
cannot import name 'wrap' from 'nes_py.wrappers'

### ISSUE THREAD

**Issue by pratikkumar** [Kautenja/playing-mario-with-deep-reinforcement-learning#38]
```
(venv) pratikku@pratikku-mac playing-mario-with-deep-reinforcement-learning master*$ python . -h
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 6, in <module>
    from src.cli import main
  File "./src/cli.py", line 3, in <module>
    from .train import train
  File "./src/train.py", line 7, in <module>
    from .setup_env import setup_env
  File "./src/setup_env.py", line 3, in <module>
    from nes_py.wrappers import BinarySpaceToDiscreteSpaceEnv, wrap as nes_py_wrap
ImportError: cannot import name 'wrap' from 'nes_py.wrappers' (/Users/pratikku/Documents/cs221-project/venv/lib/python3.7/site-packages/nes_py/wrappers/__init__.py)
```

Versions:
```gym                  0.12.5
gym-pull             0.1.7
gym-retro            0.7.0
gym-super-mario-bros 7.2.1
gym-tetris           2.2.2
nes-py               7.0.1```

**Comment by Kautenja** [comment]
ah, yea I deprecated the wrappers in nes-py and forget about that over here. I plan to publish the wrappers in a separate repo since I use them all over and will link things together when I do that sometime this week.
