### ISSUE TITLE
cannot run "python . -m play -o results/SuperMarioBros-1-4-v0/DeepQAgent/2018-08-18_18-33"

### ISSUE THREAD

**Issue by Splaver080** [Kautenja/playing-mario-with-deep-reinforcement-learning#39]
I want to see the movement of a learned agent.
I tried to run "python . -m play -o results/SuperMarioBros-1-4-v0/DeepQAgent/2018-08-18_18-33" .
But the following error was output.

Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 8, in <module>
    main()
  File "./src/cli.py", line 66, in main
    monitor=args.monitor,
  File "./src/play.py", line 68, in play
    env = setup_env(env_id, monitor_dir)
  File "./src/setup_env.py", line 27, in setup_env
    env = gym_super_mario_bros.make(env_id)
  File "/home/miyajima/.env/lib/python3.5/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/miyajima/.env/lib/python3.5/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/miyajima/.env/lib/python3.5/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/miyajima/.env/lib/python3.5/site-packages/gym_super_mario_bros/smb_env.py", line 41, in __init__
    max_episode_steps=max_episode_steps,
TypeError: __init__() got an unexpected keyword argument 'frames_per_step'

How can I solve it?

Versions:
gym==0.10.9
gym-super-mario-bros==6.0.1
nes-py==8.0.2

**Comment by Splaver080** [comment]
I upgraded gym-super-mario-bros, and this error don't raise.

Thanks.
